// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gateway/gateway.proto

package echo_micro_api_gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_087b5f483fc0b5df, []int{0}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// A HTTP request as RPC
// Forward by the api handler
type Request struct {
	Method               string           `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Get                  map[string]*Pair `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Post                 map[string]*Pair `protobuf:"bytes,5,rep,name=post,proto3" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Url                  string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_087b5f483fc0b5df, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// A HTTP response as RPC
// Expected response for the api handler
type Response struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_087b5f483fc0b5df, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "echo.micro.api.gateway.Pair")
	proto.RegisterType((*Request)(nil), "echo.micro.api.gateway.Request")
	proto.RegisterMapType((map[string]*Pair)(nil), "echo.micro.api.gateway.Request.GetEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "echo.micro.api.gateway.Request.HeaderEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "echo.micro.api.gateway.Request.PostEntry")
	proto.RegisterType((*Response)(nil), "echo.micro.api.gateway.Response")
	proto.RegisterMapType((map[string]*Pair)(nil), "echo.micro.api.gateway.Response.HeaderEntry")
}

func init() {
	proto.RegisterFile("proto/gateway/gateway.proto", fileDescriptor_087b5f483fc0b5df)
}

var fileDescriptor_087b5f483fc0b5df = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0xfa, 0x43, 0x81, 0xcb, 0xe6, 0xcb, 0x2c, 0xc8, 0x04, 0x8d, 0x36, 0x5d, 0xd5, 0x68,
	0xaa, 0xa9, 0x1b, 0x43, 0xe2, 0x0a, 0x0d, 0x26, 0x6e, 0x48, 0xe3, 0xcf, 0x7a, 0xa0, 0x37, 0x94,
	0x58, 0x98, 0xda, 0x99, 0x6a, 0xfa, 0x38, 0x3e, 0x98, 0xef, 0x62, 0x3a, 0x1d, 0x90, 0x05, 0xa4,
	0x1b, 0x5c, 0x75, 0xe6, 0xce, 0x3d, 0x27, 0xf7, 0x9c, 0x73, 0x0b, 0x47, 0x59, 0xce, 0x25, 0xbf,
	0x9c, 0x33, 0x89, 0x9f, 0xac, 0x5c, 0x7f, 0x03, 0x55, 0x25, 0x7d, 0x9c, 0x25, 0x3c, 0x58, 0x2e,
	0x66, 0x39, 0x0f, 0x58, 0xb6, 0x08, 0xf4, 0xab, 0x77, 0x05, 0xf6, 0x84, 0x2d, 0x72, 0xf2, 0x1f,
	0xac, 0x37, 0x2c, 0xa9, 0xe1, 0x1a, 0x7e, 0x37, 0xaa, 0x8e, 0xa4, 0x0f, 0xce, 0x07, 0x4b, 0x0b,
	0x14, 0xd4, 0x74, 0x2d, 0xbf, 0x1b, 0xe9, 0x9b, 0xf7, 0x65, 0x43, 0x3b, 0xc2, 0xf7, 0x02, 0x85,
	0xac, 0x7a, 0x96, 0x28, 0x13, 0x1e, 0x6b, 0xa0, 0xbe, 0x11, 0x02, 0x76, 0xc6, 0x64, 0x42, 0x4d,
	0x55, 0x55, 0x67, 0x32, 0x02, 0x27, 0x41, 0x16, 0x63, 0x4e, 0x2d, 0xd7, 0xf2, 0x7b, 0xe1, 0x79,
	0xb0, 0x7b, 0xa4, 0x40, 0x93, 0x07, 0x0f, 0xaa, 0xfb, 0x7e, 0x25, 0xf3, 0x32, 0xd2, 0x50, 0x32,
	0x04, 0x6b, 0x8e, 0x92, 0xda, 0x8a, 0xc1, 0x6f, 0x62, 0x18, 0xa3, 0xac, 0xe1, 0x15, 0x88, 0xdc,
	0x82, 0x9d, 0x71, 0x21, 0x69, 0x4b, 0x81, 0xcf, 0x9a, 0xc0, 0x13, 0x2e, 0x34, 0x5a, 0xc1, 0x2a,
	0x4d, 0x53, 0x1e, 0x97, 0xd4, 0xa9, 0x35, 0x55, 0xe7, 0xca, 0xb5, 0x22, 0x4f, 0x69, 0xbb, 0x76,
	0xad, 0xc8, 0xd3, 0xc1, 0x2b, 0xf4, 0xb6, 0xe6, 0xde, 0x61, 0x6b, 0x08, 0x2d, 0x65, 0xa4, 0xf2,
	0xa6, 0x17, 0x1e, 0xef, 0x1b, 0xa3, 0x4a, 0x25, 0xaa, 0x5b, 0x87, 0xe6, 0x8d, 0x31, 0x78, 0x82,
	0xce, 0x5a, 0xce, 0x01, 0x59, 0x9f, 0xa1, 0xbb, 0xd1, 0x79, 0x38, 0x5a, 0xef, 0xdb, 0x80, 0x4e,
	0x84, 0x22, 0xe3, 0x2b, 0x81, 0xe4, 0x04, 0x40, 0x48, 0x26, 0x0b, 0x31, 0xe2, 0x31, 0x2a, 0xf6,
	0x56, 0xb4, 0x55, 0x21, 0x77, 0x9b, 0xc5, 0x30, 0x55, 0x32, 0x17, 0xfb, 0x93, 0xa9, 0x19, 0x77,
	0x6e, 0xc6, 0x3a, 0x1e, 0xeb, 0x37, 0x9e, 0x3f, 0x0b, 0x23, 0x7c, 0x81, 0xf6, 0xb8, 0x7e, 0x22,
	0x8f, 0x60, 0x8f, 0x58, 0x9a, 0x92, 0xd3, 0x86, 0x7d, 0x1a, 0xb8, 0x4d, 0xb2, 0xbc, 0x7f, 0x53,
	0x47, 0xfd, 0xac, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xfb, 0xcc, 0xc8, 0xcb, 0x03,
	0x00, 0x00,
}
